name: mobile_final
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1



dependencies:
  flutter:
    sdk: flutter
  weatherapi: ^1.1.0
  http: 1.3.0
  xml: ^6.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/weathericon.png
  uses-material-design: true
